/**
 * Emit a standalone .mjs that renders a sample PDF for a Template Spec — the
 * "a template is portable code" goal. Run it from the project root with:
 *   node <name>.mjs
 */
import type { TemplateSpec } from '../../store/template-store';

export function templateToMjs(spec: TemplateSpec, name: string): string {
  const slug = (name || 'template').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  return `/**
 * ${name} — render a sample storybook page from this template.
 * Generated by iStorybook. Run from the project root:
 *   node ${slug}.mjs
 */
import fs from 'node:fs';
import { buildFromTemplate } from './server/services/pdf-from-template.js';
import { SAMPLE_STORY, SAMPLE_COVER, SAMPLE_SCENE_IMAGES } from './server/services/sample-image.js';

const spec = ${JSON.stringify(spec, null, 2)};

const bytes = await buildFromTemplate(spec, SAMPLE_STORY, SAMPLE_SCENE_IMAGES, SAMPLE_COVER);
fs.writeFileSync('${slug}-sample.pdf', Buffer.from(bytes));
console.log('Wrote ${slug}-sample.pdf (' + bytes.length + ' bytes)');
`;
}

export function downloadMjs(spec: TemplateSpec, name: string) {
  const code = templateToMjs(spec, name);
  const slug = (name || 'template').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([code], { type: 'text/javascript' }));
  a.download = `${slug}.mjs`;
  a.click();
  URL.revokeObjectURL(a.href);
}
